# Cloudflare Pages 配置文件
[build]
  command = "chmod +x build.sh && ./build.sh"
  publish = "dist"
  node_version = "20"

[build.environment]
  NODE_VERSION = "20"
  NPM_VERSION = "10"
  NODE_OPTIONS = "--max-old-space-size=4096" 